<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Customize\Repository;

use Doctrine\Common\Collections\ArrayCollection;
use Eccube\Entity\News;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Eccube\Repository\NewsRepository
{
    /**
     * @return News[]|ArrayCollection
     */
    public function getList()
    {
        $qb = $this->createQueryBuilder('n');
        $results = $qb->where('n.visible = :visible')
        ->andWhere('n.publish_date <= :today')
        ->andWhere('n.create_date >= :twoYearsAgo')
        ->setParameter('visible', true)
        ->setParameter('today', new \DateTime())
        ->setParameter('twoYearsAgo', (new \DateTime())->modify('-2 years'))
        ->orderBy('n.publish_date', 'DESC')
        ->addOrderBy('n.id', 'DESC')
        ->getQuery()
        ->getResult();

        return new ArrayCollection($results);
    }
}
