<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Customize\Repository;

use Customize\Common\Constants;
use Customize\Entity\UserRegisterMetas;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Common\EccubeConfig;
use Eccube\Doctrine\Query\Queries;
use Eccube\Repository\AbstractRepository;

/**
 * UserRegisterMetasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRegisterMetasRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    /**
     * @var EccubeConfig
     */
    protected $eccubeConfig;

    protected $entityManagerInterface;

    /**
     * ProductRepository constructor.
     *
     * @param RegistryInterface $registry
     * @param Queries $queries
     * @param EccubeConfig $eccubeConfig
     * @param EntityManagerInterface $entityManagerInterface
     */
    public function __construct(
        RegistryInterface $registry,
        Queries $queries,
        EccubeConfig $eccubeConfig,
        EntityManagerInterface $entityManagerInterface,
    ) {
        parent::__construct($registry, UserRegisterMetas::class);
        $this->queries = $queries;
        $this->eccubeConfig = $eccubeConfig;
        $this->entityManagerInterface = $entityManagerInterface;
    }

    public function create($customerId)
    {
        try {
            $registerIp = $this->getCLientIp();

            if (!$this->checkRegisterConditions($registerIp)) {
                return false;
            }

            $userMetas = new UserRegisterMetas();

            $userMetas->setCustomerId($customerId);
            $userMetas->setStatus(true);
            $userMetas->setUserAgent($this->getUserAgent());
            $userMetas->setUserIp($registerIp);
            $userMetas->setCreatedAt(new \DateTime());

            $this->entityManagerInterface->persist($userMetas);
            $this->entityManagerInterface->flush();

            return true;
        } catch (\Exception $th) {
            return false;
        }
    }

    private function getCLientIp()
    {
        $clientIP = isset($_SERVER['HTTP_CLIENT_IP'])
            ? $_SERVER['HTTP_CLIENT_IP']
            : (isset($_SERVER['HTTP_X_FORWARDED_FOR'])
            ? $_SERVER['HTTP_X_FORWARDED_FOR']
            : $_SERVER['REMOTE_ADDR']);

        if ($clientIP) {
            return $clientIP;
        }

        throw new \Exception("Can't get IP");
    }

    private function getUserAgent()
    {
        return isset($_SERVER['HTTP_USER_AGENT']) ? $_SERVER['HTTP_USER_AGENT'] : '';
    }

    private function checkRegisterConditions($regiserIp)
    {
        $pdo = $this->entityManagerInterface->getConnection();
        $sql = "SELECT * FROM `user_register_metas` where Date(created_at) = CURDATE() and user_ip = '{$regiserIp}'";
        $stmt = $pdo->executeQuery($sql);

        $result = $stmt->fetchAllAssociative();
        $allowRegiterInDay = Constants::ALLOW_REGISTER_A_DAY;
        $countIpRegisterInDay = count($result);

        // Check Register of the IP in 24 hour
        if ($countIpRegisterInDay >= $allowRegiterInDay) {
            return false;
        }

        return true;
    }
}
